### ISSUE TITLE
malformed packet crash

### ISSUE THREAD

**Issue by fredericosilva** [infusion/node-dhcp#5]
Hello,

If packet is malformed node-dhcp crashes, do you have some thoughts how to handle this?

```
TypeError: Cannot read property 'join' of null
    at SeqBuffer.getMAC (.../node-dhcp/lib/seqbuffer.js:162:42)
    at Object.parse (.../node-dhcp/lib/protocol.js:23:18)
    at Socket.<anonymous> (.../node-dhcp/lib/dhcp.js:66:24)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8)
```

Keep up the good work :)

**Comment by infusion** [comment]
Hi Frederico,

sorry for the error. Must be something I just pushed in 0.2.0. I'll look into that!

And thanks! =)

**Comment by infusion** [comment]
Uhm, okay that's really strange. Could you please provide some more info? 

- What operating system are you on?
- Are you going to test the server or client?
- Is this an own script using the dhcp lib, or the server/client example or cli binary?
- Could you please verify os.networkInterfaces(); at line 516 of dhcp.js returns something meaningful?

The strange thing is, that it fails on parsing the incoming DHCP package, exactly when the mac-address is getting parsed.

**Comment by fredericosilva** [comment]
I'm testing the robustness of the server when the client sends a malformed packet.

Something like
```
dgram.createSocket('udp4').send("asdas", 67, ...)
```
crashes the server with that error
```
TypeError: Cannot read property 'join' of null
    at SeqBuffer.getMAC (.../node-dhcp/lib/seqbuffer.js:162:42)
    at Object.parse (.../node-dhcp/lib/protocol.js:23:18)
    at Socket.<anonymous> (.../node-dhcp/lib/dhcp.js:66:24)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8)
```
Let me know if you need further info.

**Comment by infusion** [comment]
Ahh, okay! That's a good one. Thanks for testing malformed packages. Could you please check out v0.2.2 and test it again? THX!

**Comment by fredericosilva** [comment]
Still getting the same error
```
.../node-dhcp/lib/seqbuffer.js:162
    return mac.toUpperCase().match(/../g).join('-');
                                         ^
TypeError: Cannot read property 'join' of null
    at SeqBuffer.getMAC (.../node-dhcp/lib/seqbuffer.js:162:42)
    at Object.parse (.../node-dhcp/lib/protocol.js:25:18)
    at Socket.<anonymous> (.../node-dhcp/lib/dhcp.js:60:24)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8)
```
Maybe you should wrap everything on a try..catch?

**Comment by infusion** [comment]
Hum? That's really strange. My test-script is this:

```
const dgram = require('dgram');

var sock = dgram.createSocket('udp4');

var foo = "blabla";

sock.send(foo, 0, foo.length, 67, "0.0.0.0", function(err, bytes) {
        console.log(err, bytes);
});
```
On the other side, I receive the data via:

```
➜  dhcp git:(master) ✗ node examples/client.js
Send Discover
Client Listening: 0.0.0.0:67
Sent  270 bytes
6 <Buffer 62 6c 61 62 6c 61>
Error: Malformed packet
    at Socket.<anonymous> (/Users/robert/Desktop/WORK/_publish/dhcp/lib/dhcp.js:465:26)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8) <Buffer 62 6c 61 62 6c 61>
```

The line `6 <Buffer 62 6c 61 62 6c 61>` comes from `console.log(buf.length, buf)`, I wrote right before the `buf.length < Protocol.MIN_BUFFER_LENGTH` check.

A try-catch would be the lazy last resort to come up with this problem. Before that, I'd like to understand the problem.

**Comment by fredericosilva** [comment]
I'm sending to the server. Using your test-script I can reproduce the error.

```
# node examples/server.js
Server Listening: 0.0.0.0:67
/root/sandbox/node-dhcp/lib/seqbuffer.js:162
    return mac.toUpperCase().match(/../g).join('-');
                                         ^

TypeError: Cannot read property 'join' of null
    at SeqBuffer.getMAC (/root/sandbox/node-dhcp/lib/seqbuffer.js:162:42)
    at Object.parse (/root/sandbox/node-dhcp/lib/protocol.js:25:18)
    at Socket.<anonymous> (/root/sandbox/node-dhcp/lib/dhcp.js:60:24)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8)

**Comment by infusion** [comment]
Sorry, I forgot something. Hope it works now.

**Comment by fredericosilva** [comment]
I does work now :)

I've a new malformed package for you
```
dgram.createSocket('udp4').send(Array(250).join('a'), 67, "0.0.0.0", console.log)
```
```
# node examples/server.js
Server Listening: 0.0.0.0:67
/root/sandbox/node-dhcp/lib/seqbuffer.js:169
      throw new Error('Invalid hardware address length ' + hlen);
      ^

Error: Invalid hardware address length 97
    at SeqBuffer.getMAC (/root/sandbox/node-dhcp/lib/seqbuffer.js:169:13)
    at Object.parse (/root/sandbox/node-dhcp/lib/protocol.js:34:18)
    at Socket.<anonymous> (/root/sandbox/node-dhcp/lib/dhcp.js:72:24)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:623:8)

**Comment by fredericosilva** [comment]
Try...catch from 1a9c9537baf464db93a3a17a6c9c6758c7879e81 fixes this issue. tks :)
